version: '3.3'

services:
  postgres:
    container_name: coemu-db
    image: postgres:12
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ~/.data/coemu:/var/lib/postgresql/data
