[package]
name = "gamemap-decoder"
version = "0.1.0"
authors = ["Shady Khalifa <dev@shadykhalifa.me>"]
edition.workspace = true

[dependencies]
dotenvy.workspace = true
bytes.workspace = true
anyhow.workspace = true
serde.workspace = true
csv = "1"
