[package]
name = "game-server"
version = "0.1.0"
authors = ["Shady Khalifa <shekohex@gmail.com>"]
edition = "2018"


[dependencies]
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
bytes = "0.5"
tq-network = { path = "../../core/network" }
tq-serde = { path = "../../core/serde" }
tq-math = { path = "../../core/math" }
primitives = { path = "../../core/primitives" }
async-trait = "0.1"
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = { version = "0.2", default-features = false, features = ["env-filter", "ansi", "fmt", "chrono", "smallvec"] }
dotenv = "0.15"
once_cell = "1.4"
chrono = { version = "0.4", default-features = false, features = ["std"] }
fastrand = "1.3"
encoding = "0.2"
bitflags = "1.2"
argh = "0.1"

# Utils
[dependencies.num_enum]
version = "0.5.1"
default-features = false

# Runtime
[dependencies.tokio]
version = "0.2"
default-features = false
features = ["rt-threaded", "macros", "signal", "stream", "sync", "parking_lot"]

# Database
[dependencies.sqlx]
version = "0.4.0-beta.1"
default-features = false
features = ["runtime-tokio", "macros", "postgres", "ipnetwork", "chrono", "offline"]
