[alias]
auth = "run --bin auth-server"
game = "run --bin game-server"
hash-pwd = "run --bin hash-pwd"

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = ["-Zshare-generics=n", "--cfg", "tokio_unstable"]
