[package]
name = "auth-server"
version = "0.1.0"
authors = ["Shady Khalifa <shekohex@gmail.com>"]
edition = "2018"

[dependencies]
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
bytes = "1.1"
tq-network = { path = "../../core/network" }
tq-serde = { path = "../../core/serde" }
async-trait = "0.1"
tracing = "0.1"
tracing-futures = "0.2"
dotenv = "0.15"
once_cell = "1.4"
chrono = { version = "0.4", default-features = false, features = ["std"] }
bcrypt = "0.12"
num_enum = { version = "0.5.7", default-features = false }

[dependencies.tracing-subscriber]
version = "0.3"
default-features = false
features = ["env-filter", "ansi", "fmt", "chrono", "smallvec"]

# Runtime
[dependencies.tokio]
version = "1.17"
default-features = false
features = ["rt-threaded", "macros", "signal"]

# Database
[dependencies.sqlx]
version = "0.4.0-beta.1"
default-features = false
features = ["runtime-tokio", "macros", "postgres", "ipnetwork", "chrono", "offline"]
