[package]
name = "auth-server"
version = "0.1.0"
authors = ["Shady Khalifa <dev@shadykhalifa.me>"]
edition.workspace = true

[dependencies]
thiserror.workspace = true
serde.workspace = true
bytes.workspace = true
tq-network.workspace = true
tq-serde.workspace = true
tq-db.workspace = true
async-trait.workspace = true
tracing.workspace = true
dotenvy.workspace = true
once_cell.workspace = true
num_enum = { workspace = true, default-features = false }
tokio-stream.workspace = true

[dependencies.tracing-subscriber]
version = "0.3"
default-features = false
features = ["env-filter", "ansi", "fmt", "smallvec"]

# Runtime
[dependencies.tokio]
workspace = true
default-features = false
features = ["rt-multi-thread", "macros", "signal"]

# Database
[dependencies.sqlx]
workspace = true
default-features = false
features = ["runtime-tokio-rustls", "sqlite", "macros"]
